version: '3.8'
services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_USER=mysql
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"